// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/definition/repository/write_definition_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:teigiii_api/src/api/definitions_api.dart' as _i3;
import 'package:teigiii_api/src/model/create_definition_request.dart' as _i8;
import 'package:teigiii_api/src/model/definition_response.dart' as _i5;
import 'package:teigiii_api/src/model/update_definition_request.dart' as _i7;
import 'package:teigiii_api/src/model/v1_users_id_followers_get200_response.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DefinitionsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefinitionsApi extends _i1.Mock implements _i3.DefinitionsApi {
  @override
  _i4.Future<_i2.Response<void>> v1DefinitionsIdDelete({
    required String? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1DefinitionsIdDelete,
          [],
          {
            #id: id,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i4.Future<_i2.Response<void>>.value(_FakeResponse_0<void>(
          this,
          Invocation.method(
            #v1DefinitionsIdDelete,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<void>>.value(_FakeResponse_0<void>(
          this,
          Invocation.method(
            #v1DefinitionsIdDelete,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<void>>);

  @override
  _i4.Future<_i2.Response<_i5.DefinitionResponse>> v1DefinitionsIdGet({
    required String? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1DefinitionsIdGet,
          [],
          {
            #id: id,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i4.Future<_i2.Response<_i5.DefinitionResponse>>.value(
            _FakeResponse_0<_i5.DefinitionResponse>(
          this,
          Invocation.method(
            #v1DefinitionsIdGet,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<_i5.DefinitionResponse>>.value(
                _FakeResponse_0<_i5.DefinitionResponse>(
          this,
          Invocation.method(
            #v1DefinitionsIdGet,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.DefinitionResponse>>);

  @override
  _i4.Future<_i2.Response<void>> v1DefinitionsIdLikeDelete({
    required String? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1DefinitionsIdLikeDelete,
          [],
          {
            #id: id,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i4.Future<_i2.Response<void>>.value(_FakeResponse_0<void>(
          this,
          Invocation.method(
            #v1DefinitionsIdLikeDelete,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<void>>.value(_FakeResponse_0<void>(
          this,
          Invocation.method(
            #v1DefinitionsIdLikeDelete,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<void>>);

  @override
  _i4.Future<_i2.Response<void>> v1DefinitionsIdLikePut({
    required String? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1DefinitionsIdLikePut,
          [],
          {
            #id: id,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i4.Future<_i2.Response<void>>.value(_FakeResponse_0<void>(
          this,
          Invocation.method(
            #v1DefinitionsIdLikePut,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<void>>.value(_FakeResponse_0<void>(
          this,
          Invocation.method(
            #v1DefinitionsIdLikePut,
            [],
            {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<void>>);

  @override
  _i4.Future<_i2.Response<_i6.V1UsersIdFollowersGet200Response>>
      v1DefinitionsIdLikesGet({
    required String? id,
    String? cursor,
    int? limit = 20,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #v1DefinitionsIdLikesGet,
              [],
              {
                #id: id,
                #cursor: cursor,
                #limit: limit,
                #cancelToken: cancelToken,
                #headers: headers,
                #extra: extra,
                #validateStatus: validateStatus,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i4.Future<
                    _i2.Response<_i6.V1UsersIdFollowersGet200Response>>.value(
                _FakeResponse_0<_i6.V1UsersIdFollowersGet200Response>(
              this,
              Invocation.method(
                #v1DefinitionsIdLikesGet,
                [],
                {
                  #id: id,
                  #cursor: cursor,
                  #limit: limit,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
            returnValueForMissingStub: _i4.Future<
                    _i2.Response<_i6.V1UsersIdFollowersGet200Response>>.value(
                _FakeResponse_0<_i6.V1UsersIdFollowersGet200Response>(
              this,
              Invocation.method(
                #v1DefinitionsIdLikesGet,
                [],
                {
                  #id: id,
                  #cursor: cursor,
                  #limit: limit,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                },
              ),
            )),
          ) as _i4.Future<_i2.Response<_i6.V1UsersIdFollowersGet200Response>>);

  @override
  _i4.Future<_i2.Response<_i5.DefinitionResponse>> v1DefinitionsIdPatch({
    required String? id,
    _i7.UpdateDefinitionRequest? updateDefinitionRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1DefinitionsIdPatch,
          [],
          {
            #id: id,
            #updateDefinitionRequest: updateDefinitionRequest,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i4.Future<_i2.Response<_i5.DefinitionResponse>>.value(
            _FakeResponse_0<_i5.DefinitionResponse>(
          this,
          Invocation.method(
            #v1DefinitionsIdPatch,
            [],
            {
              #id: id,
              #updateDefinitionRequest: updateDefinitionRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<_i5.DefinitionResponse>>.value(
                _FakeResponse_0<_i5.DefinitionResponse>(
          this,
          Invocation.method(
            #v1DefinitionsIdPatch,
            [],
            {
              #id: id,
              #updateDefinitionRequest: updateDefinitionRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.DefinitionResponse>>);

  @override
  _i4.Future<_i2.Response<_i5.DefinitionResponse>> v1DefinitionsPost({
    _i8.CreateDefinitionRequest? createDefinitionRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1DefinitionsPost,
          [],
          {
            #createDefinitionRequest: createDefinitionRequest,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i4.Future<_i2.Response<_i5.DefinitionResponse>>.value(
            _FakeResponse_0<_i5.DefinitionResponse>(
          this,
          Invocation.method(
            #v1DefinitionsPost,
            [],
            {
              #createDefinitionRequest: createDefinitionRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Response<_i5.DefinitionResponse>>.value(
                _FakeResponse_0<_i5.DefinitionResponse>(
          this,
          Invocation.method(
            #v1DefinitionsPost,
            [],
            {
              #createDefinitionRequest: createDefinitionRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i4.Future<_i2.Response<_i5.DefinitionResponse>>);
}
