// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/definition/application/definition_draft_editor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:teigi_app/feature/definition/domain/definition_draft.dart'
    as _i2;
import 'package:teigi_app/feature/definition/repository/definition_draft_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDefinitionDraft_0 extends _i1.SmartFake
    implements _i2.DefinitionDraft {
  _FakeDefinitionDraft_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DefinitionDraftRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefinitionDraftRepository extends _i1.Mock
    implements _i3.DefinitionDraftRepository {
  @override
  _i4.Future<_i2.DefinitionDraft> save(_i2.DefinitionDraft? draft) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [draft],
        ),
        returnValue:
            _i4.Future<_i2.DefinitionDraft>.value(_FakeDefinitionDraft_0(
          this,
          Invocation.method(
            #save,
            [draft],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DefinitionDraft>.value(_FakeDefinitionDraft_0(
          this,
          Invocation.method(
            #save,
            [draft],
          ),
        )),
      ) as _i4.Future<_i2.DefinitionDraft>);

  @override
  _i4.Future<_i2.DefinitionDraft> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.DefinitionDraft>.value(_FakeDefinitionDraft_0(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.DefinitionDraft>.value(_FakeDefinitionDraft_0(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.DefinitionDraft>);

  @override
  _i4.Future<({List<_i2.DefinitionDraft> items, String? nextCursor})> list({
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #cursor: cursor,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<
            ({
              List<_i2.DefinitionDraft> items,
              String? nextCursor
            })>.value((items: <_i2.DefinitionDraft>[], nextCursor: null)),
        returnValueForMissingStub: _i4.Future<
            ({
              List<_i2.DefinitionDraft> items,
              String? nextCursor
            })>.value((items: <_i2.DefinitionDraft>[], nextCursor: null)),
      ) as _i4.Future<({List<_i2.DefinitionDraft> items, String? nextCursor})>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> finalize(
    String? id, {
    bool? confirmReadingMismatch = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #finalize,
          [id],
          {#confirmReadingMismatch: confirmReadingMismatch},
        ),
        returnValue: _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #finalize,
            [id],
            {#confirmReadingMismatch: confirmReadingMismatch},
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #finalize,
            [id],
            {#confirmReadingMismatch: confirmReadingMismatch},
          ),
        )),
      ) as _i4.Future<String>);
}
