// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/definition/application/definition_write_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:teigi_app/feature/definition/domain/definition_for_write.dart'
    as _i4;
import 'package:teigi_app/feature/definition/repository/write_definition_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WriteDefinitionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWriteDefinitionRepository extends _i1.Mock
    implements _i2.WriteDefinitionRepository {
  @override
  _i3.Future<String> createDefinition(
    _i4.DefinitionForWrite? definitionForWrite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createDefinition, [definitionForWrite]),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createDefinition, [definitionForWrite]),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#createDefinition, [definitionForWrite]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> updateDefinition(
    _i4.DefinitionForWrite? definitionForWrite,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDefinition, [definitionForWrite]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updatePostType({
    required String? definitionId,
    required bool? isPublic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updatePostType, [], {
              #definitionId: definitionId,
              #isPublic: isPublic,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDefinition(String? definitionId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDefinition, [definitionId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
