// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/personal_dictionary/application/personal_dictionary_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:teigi_app/feature/definition/domain/definition_draft.dart'
    as _i5;
import 'package:teigi_app/feature/personal_dictionary/domain/personal_dictionary.dart'
    as _i2;
import 'package:teigi_app/feature/personal_dictionary/repository/personal_dictionary_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePersonalDictionaryOverview_0 extends _i1.SmartFake
    implements _i2.PersonalDictionaryOverview {
  _FakePersonalDictionaryOverview_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePagedItems_1<T> extends _i1.SmartFake implements _i2.PagedItems<T> {
  _FakePagedItems_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PersonalDictionaryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPersonalDictionaryRepository extends _i1.Mock
    implements _i3.PersonalDictionaryRepository {
  @override
  _i4.Future<_i2.PersonalDictionaryOverview> fetchOverview() =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchOverview,
          [],
        ),
        returnValue: _i4.Future<_i2.PersonalDictionaryOverview>.value(
            _FakePersonalDictionaryOverview_0(
          this,
          Invocation.method(
            #fetchOverview,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PersonalDictionaryOverview>.value(
                _FakePersonalDictionaryOverview_0(
          this,
          Invocation.method(
            #fetchOverview,
            [],
          ),
        )),
      ) as _i4.Future<_i2.PersonalDictionaryOverview>);

  @override
  _i4.Future<_i2.PagedItems<_i2.DefinedWord>> fetchDefinedWords({
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDefinedWords,
          [],
          {
            #cursor: cursor,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.PagedItems<_i2.DefinedWord>>.value(
            _FakePagedItems_1<_i2.DefinedWord>(
          this,
          Invocation.method(
            #fetchDefinedWords,
            [],
            {
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PagedItems<_i2.DefinedWord>>.value(
                _FakePagedItems_1<_i2.DefinedWord>(
          this,
          Invocation.method(
            #fetchDefinedWords,
            [],
            {
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.PagedItems<_i2.DefinedWord>>);

  @override
  _i4.Future<_i2.PagedItems<_i5.DefinitionDraft>> fetchDrafts({
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDrafts,
          [],
          {
            #cursor: cursor,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.PagedItems<_i5.DefinitionDraft>>.value(
            _FakePagedItems_1<_i5.DefinitionDraft>(
          this,
          Invocation.method(
            #fetchDrafts,
            [],
            {
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PagedItems<_i5.DefinitionDraft>>.value(
                _FakePagedItems_1<_i5.DefinitionDraft>(
          this,
          Invocation.method(
            #fetchDrafts,
            [],
            {
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.PagedItems<_i5.DefinitionDraft>>);

  @override
  _i4.Future<void> deleteDraft(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDraft,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.PagedItems<_i2.SavedWord>> fetchSavedWords({
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSavedWords,
          [],
          {
            #cursor: cursor,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i2.PagedItems<_i2.SavedWord>>.value(
            _FakePagedItems_1<_i2.SavedWord>(
          this,
          Invocation.method(
            #fetchSavedWords,
            [],
            {
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.PagedItems<_i2.SavedWord>>.value(
                _FakePagedItems_1<_i2.SavedWord>(
          this,
          Invocation.method(
            #fetchSavedWords,
            [],
            {
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i2.PagedItems<_i2.SavedWord>>);
}
