// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/core/page/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:teigi_app/feature/definition_list/domain/definition_id_list_state.dart'
    as _i3;
import 'package:teigi_app/feature/definition_list/repository/definition_id_list_repository.dart'
    as _i7;
import 'package:teigi_app/feature/definition_list/util/definition_feed_type.dart'
    as _i8;
import 'package:teigi_app/feature/timeline/domain/timeline.dart' as _i2;
import 'package:teigi_app/feature/timeline/repository/timeline_repository.dart'
    as _i4;
import 'package:teigi_app/feature/timeline/repository/timeline_tab_repository.dart'
    as _i6;
import 'package:teigi_app/util/constant/initial_main_group.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTimelinePage_0 extends _i1.SmartFake implements _i2.TimelinePage {
  _FakeTimelinePage_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDefinitionIdListState_1 extends _i1.SmartFake
    implements _i3.DefinitionIdListState {
  _FakeDefinitionIdListState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TimelineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimelineRepository extends _i1.Mock
    implements _i4.TimelineRepository {
  @override
  _i5.Future<_i2.TimelinePage> fetchDiscover({
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDiscover,
          [],
          {
            #cursor: cursor,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<_i2.TimelinePage>.value(_FakeTimelinePage_0(
          this,
          Invocation.method(
            #fetchDiscover,
            [],
            {
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.TimelinePage>.value(_FakeTimelinePage_0(
          this,
          Invocation.method(
            #fetchDiscover,
            [],
            {
              #cursor: cursor,
              #limit: limit,
            },
          ),
        )),
      ) as _i5.Future<_i2.TimelinePage>);
}

/// A class which mocks [TimelineTabRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTimelineTabRepository extends _i1.Mock
    implements _i6.TimelineTabRepository {
  @override
  _i5.Future<int> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
        returnValueForMissingStub: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> save(int? index) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [index],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [DefinitionIdListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefinitionIdListRepository extends _i1.Mock
    implements _i7.DefinitionIdListRepository {
  @override
  _i5.Future<_i3.DefinitionIdListState> fetchForHomeRecommend(String? cursor) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForHomeRecommend,
          [cursor],
        ),
        returnValue: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForHomeRecommend,
            [cursor],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForHomeRecommend,
            [cursor],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionIdListState>);

  @override
  _i5.Future<_i3.DefinitionIdListState> fetchForHomeFollowing(String? cursor) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForHomeFollowing,
          [cursor],
        ),
        returnValue: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForHomeFollowing,
            [cursor],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForHomeFollowing,
            [cursor],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionIdListState>);

  @override
  _i5.Future<_i3.DefinitionIdListState> fetchForWordMine(
    String? wordId,
    String? cursor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForWordMine,
          [
            wordId,
            cursor,
          ],
        ),
        returnValue: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForWordMine,
            [
              wordId,
              cursor,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForWordMine,
            [
              wordId,
              cursor,
            ],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionIdListState>);

  @override
  _i5.Future<_i3.DefinitionIdListState> fetchForWordOthers(
    _i8.WordTopOrderByType? orderByType,
    String? wordId,
    String? cursor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForWordOthers,
          [
            orderByType,
            wordId,
            cursor,
          ],
        ),
        returnValue: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForWordOthers,
            [
              orderByType,
              wordId,
              cursor,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForWordOthers,
            [
              orderByType,
              wordId,
              cursor,
            ],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionIdListState>);

  @override
  _i5.Future<_i3.DefinitionIdListState> fetchForProfileCreatedAt(
    String? targetUserId,
    String? cursor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForProfileCreatedAt,
          [
            targetUserId,
            cursor,
          ],
        ),
        returnValue: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForProfileCreatedAt,
            [
              targetUserId,
              cursor,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForProfileCreatedAt,
            [
              targetUserId,
              cursor,
            ],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionIdListState>);

  @override
  _i5.Future<_i3.DefinitionIdListState> fetchForLikedByUser(
    String? targetUserId,
    String? cursor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForLikedByUser,
          [
            targetUserId,
            cursor,
          ],
        ),
        returnValue: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForLikedByUser,
            [
              targetUserId,
              cursor,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForLikedByUser,
            [
              targetUserId,
              cursor,
            ],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionIdListState>);

  @override
  _i5.Future<_i3.DefinitionIdListState> fetchForIndividualDictionary(
    String? targetUserId,
    _i9.InitialSubGroup? initialSubGroup,
    String? cursor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchForIndividualDictionary,
          [
            targetUserId,
            initialSubGroup,
            cursor,
          ],
        ),
        returnValue: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForIndividualDictionary,
            [
              targetUserId,
              initialSubGroup,
              cursor,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.DefinitionIdListState>.value(
            _FakeDefinitionIdListState_1(
          this,
          Invocation.method(
            #fetchForIndividualDictionary,
            [
              targetUserId,
              initialSubGroup,
              cursor,
            ],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionIdListState>);
}
