// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/word/repository/word_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:teigiii_api/src/api/words_api.dart' as _i3;
import 'package:teigiii_api/src/model/create_word_request.dart' as _i11;
import 'package:teigiii_api/src/model/create_word_response.dart' as _i10;
import 'package:teigiii_api/src/model/update_word_request.dart' as _i8;
import 'package:teigiii_api/src/model/v1_users_id_definitions_get200_response.dart'
    as _i6;
import 'package:teigiii_api/src/model/v1_words_get200_response.dart' as _i5;
import 'package:teigiii_api/src/model/word_lookup_response.dart' as _i9;
import 'package:teigiii_api/src/model/word_response.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WordsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordsApi extends _i1.Mock implements _i3.WordsApi {
  @override
  _i4.Future<_i2.Response<_i5.V1WordsGet200Response>> v1WordsGet({
    String? cursor,
    int? limit = 20,
    String? subGroup,
    String? filter = r'all',
    String? q,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1WordsGet, [], {
              #cursor: cursor,
              #limit: limit,
              #subGroup: subGroup,
              #filter: filter,
              #q: q,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i5.V1WordsGet200Response>>.value(
                  _FakeResponse_0<_i5.V1WordsGet200Response>(
                    this,
                    Invocation.method(#v1WordsGet, [], {
                      #cursor: cursor,
                      #limit: limit,
                      #subGroup: subGroup,
                      #filter: filter,
                      #q: q,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Response<_i5.V1WordsGet200Response>>.value(
                  _FakeResponse_0<_i5.V1WordsGet200Response>(
                    this,
                    Invocation.method(#v1WordsGet, [], {
                      #cursor: cursor,
                      #limit: limit,
                      #subGroup: subGroup,
                      #filter: filter,
                      #q: q,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i5.V1WordsGet200Response>>);

  @override
  _i4.Future<_i2.Response<_i6.V1UsersIdDefinitionsGet200Response>>
  v1WordsIdDefinitionsGet({
    required String? id,
    String? cursor,
    int? limit = 20,
    String? scope = r'all',
    String? sort = r'newest',
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1WordsIdDefinitionsGet, [], {
              #id: id,
              #cursor: cursor,
              #limit: limit,
              #scope: scope,
              #sort: sort,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<
                  _i2.Response<_i6.V1UsersIdDefinitionsGet200Response>
                >.value(
                  _FakeResponse_0<_i6.V1UsersIdDefinitionsGet200Response>(
                    this,
                    Invocation.method(#v1WordsIdDefinitionsGet, [], {
                      #id: id,
                      #cursor: cursor,
                      #limit: limit,
                      #scope: scope,
                      #sort: sort,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Response<_i6.V1UsersIdDefinitionsGet200Response>
                >.value(
                  _FakeResponse_0<_i6.V1UsersIdDefinitionsGet200Response>(
                    this,
                    Invocation.method(#v1WordsIdDefinitionsGet, [], {
                      #id: id,
                      #cursor: cursor,
                      #limit: limit,
                      #scope: scope,
                      #sort: sort,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i6.V1UsersIdDefinitionsGet200Response>>);

  @override
  _i4.Future<_i2.Response<_i7.WordResponse>> v1WordsIdGet({
    required String? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1WordsIdGet, [], {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i7.WordResponse>>.value(
              _FakeResponse_0<_i7.WordResponse>(
                this,
                Invocation.method(#v1WordsIdGet, [], {
                  #id: id,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Response<_i7.WordResponse>>.value(
                  _FakeResponse_0<_i7.WordResponse>(
                    this,
                    Invocation.method(#v1WordsIdGet, [], {
                      #id: id,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i7.WordResponse>>);

  @override
  _i4.Future<_i2.Response<_i7.WordResponse>> v1WordsIdPatch({
    required String? id,
    _i8.UpdateWordRequest? updateWordRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1WordsIdPatch, [], {
              #id: id,
              #updateWordRequest: updateWordRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i7.WordResponse>>.value(
              _FakeResponse_0<_i7.WordResponse>(
                this,
                Invocation.method(#v1WordsIdPatch, [], {
                  #id: id,
                  #updateWordRequest: updateWordRequest,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Response<_i7.WordResponse>>.value(
                  _FakeResponse_0<_i7.WordResponse>(
                    this,
                    Invocation.method(#v1WordsIdPatch, [], {
                      #id: id,
                      #updateWordRequest: updateWordRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i7.WordResponse>>);

  @override
  _i4.Future<_i2.Response<void>> v1WordsIdSaveDelete({
    required String? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1WordsIdSaveDelete, [], {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<void>>.value(
              _FakeResponse_0<void>(
                this,
                Invocation.method(#v1WordsIdSaveDelete, [], {
                  #id: id,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Response<void>>.value(
              _FakeResponse_0<void>(
                this,
                Invocation.method(#v1WordsIdSaveDelete, [], {
                  #id: id,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<void>>);

  @override
  _i4.Future<_i2.Response<void>> v1WordsIdSavePut({
    required String? id,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1WordsIdSavePut, [], {
              #id: id,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<void>>.value(
              _FakeResponse_0<void>(
                this,
                Invocation.method(#v1WordsIdSavePut, [], {
                  #id: id,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.Response<void>>.value(
              _FakeResponse_0<void>(
                this,
                Invocation.method(#v1WordsIdSavePut, [], {
                  #id: id,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response<void>>);

  @override
  _i4.Future<_i2.Response<_i9.WordLookupResponse>> v1WordsLookupGet({
    required String? word,
    required String? reading,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1WordsLookupGet, [], {
              #word: word,
              #reading: reading,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i9.WordLookupResponse>>.value(
              _FakeResponse_0<_i9.WordLookupResponse>(
                this,
                Invocation.method(#v1WordsLookupGet, [], {
                  #word: word,
                  #reading: reading,
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Response<_i9.WordLookupResponse>>.value(
                  _FakeResponse_0<_i9.WordLookupResponse>(
                    this,
                    Invocation.method(#v1WordsLookupGet, [], {
                      #word: word,
                      #reading: reading,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i9.WordLookupResponse>>);

  @override
  _i4.Future<_i2.Response<_i10.CreateWordResponse>> v1WordsPost({
    _i11.CreateWordRequest? createWordRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1WordsPost, [], {
              #createWordRequest: createWordRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i4.Future<_i2.Response<_i10.CreateWordResponse>>.value(
                  _FakeResponse_0<_i10.CreateWordResponse>(
                    this,
                    Invocation.method(#v1WordsPost, [], {
                      #createWordRequest: createWordRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Response<_i10.CreateWordResponse>>.value(
                  _FakeResponse_0<_i10.CreateWordResponse>(
                    this,
                    Invocation.method(#v1WordsPost, [], {
                      #createWordRequest: createWordRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i10.CreateWordResponse>>);
}
