import 'package:cloud_firestore/cloud_firestore.dart';

Future<void> addDefinitionsToFirestore() async {
  final firestore = FirebaseFirestore.instance;

  // 上で定義したdefinitionsマップを用いてデータをFirestoreに追加
  for (final definitionId in definitions.keys) {
    final definition = definitions[definitionId]!;
    await firestore.collection('Definitions').doc(definitionId).set({
      ...definition,
      'createdAt': FieldValue.serverTimestamp(),
      'updatedAt': FieldValue.serverTimestamp(),
    });
  }
}

final definitions = {
  'definition1': {
    'wordId': 'word1',
    'authorId': 'user1',
    'content': '友情とは、相手を思いやる気持ちや、お互いの信頼に基づく関係のこと。それは言葉では表現しにくい、深い絆で結ばれている。',
    'likesCount': 5,
    'isPublic': true,
  },
  'definition2': {
    'wordId': 'word1',
    'authorId': 'user2',
    'content': '友情って、宝物だよね。大切な仲間との絆、それが私の友情の定義だ。',
    'likesCount': 15,
    'isPublic': true,
  },
  'definition3': {
    'wordId': 'word2',
    'authorId': 'user3',
    'content': '愛とは、他者の幸福を自分の幸福と同じように願う気持ち。それは自己犠牲も厭わない、強い感情だ。',
    'likesCount': 8,
    'isPublic': true,
  },
  'definition4': {
    'wordId': 'word2',
    'authorId': 'user4',
    'content': '愛は、宇宙の真理。人々が争いを超えて結ばれる最も強力な力。',
    'likesCount': 20,
    'isPublic': true,
  },
  'definition5': {
    'wordId': 'word3',
    'authorId': 'user5',
    'content': '失敗は成功のもと。失敗から学び、それをバネにして更なる高みを目指すことが大切だ。',
    'likesCount': 12,
    'isPublic': true,
  },
  'definition6': {
    'wordId': 'word4',
    'authorId': 'user6',
    'content': '成功とは、目標を達成すること。しかし、その過程や努力が真の成功を生む。',
    'likesCount': 18,
    'isPublic': true,
  },
  'definition7': {
    'wordId': 'word5',
    'authorId': 'user7',
    'content': '自由とは、束縛や制約を受けずに、自分の意志で行動すること。しかし、その自由は他者の自由を侵害してはならない。',
    'likesCount': 22,
    'isPublic': true,
  },
  'definition8': {
    'wordId': 'word6',
    'authorId': 'user8',
    'content': '平和とは、戦争や争いがない、安定した状態。人々が互いに尊重し合い、調和を保つ社会のこと。',
    'likesCount': 9,
    'isPublic': true,
  },
  'definition9': {
    'wordId': 'word7',
    'authorId': 'user9',
    'content': '冒険とは、未知の世界への挑戦。それは新しい経験や発見、そして成長をもたらす。',
    'likesCount': 7,
    'isPublic': true,
  },
  'definition10': {
    'wordId': 'word8',
    'authorId': 'user10',
    'content': '夢は、未来のビジョン。それは目標や希望を持ち、努力することで叶えることができる。',
    'likesCount': 16,
    'isPublic': true,
  },
  'definition11': {
    'wordId': 'word9',
    'authorId': 'user11',
    'content': '希望とは、良い未来を信じること。困難な状況でも、前向きな気持ちを保つ力。',
    'likesCount': 10,
    'isPublic': true,
  },
  'definition12': {
    'wordId': 'word10',
    'authorId': 'user12',
    'content': '勇気とは、恐れや不安を乗り越えて行動する力。それは目の前の困難に立ち向かう勇気だけでなく、自分の信念を貫く勇気も含まれる。',
    'likesCount': 14,
    'isPublic': true,
  },
  'definition13': {
    'wordId': 'word11',
    'authorId': 'user13',
    'content': '哲学とは、生き方や宇宙、存在についての思考。それは人間の心や精神を探求する学問である。',
    'likesCount': 5,
    'isPublic': true,
  },
  'definition14': {
    'wordId': 'word12',
    'authorId': 'user14',
    'content': '信仰とは、神や宗教的な価値観を信じること。それは人々の生活や精神を支える力となる。',
    'likesCount': 11,
    'isPublic': true,
  },
  'definition15': {
    'wordId': 'word13',
    'authorId': 'user15',
    'content': '真実とは、事実や現実を正確に表すこと。それは隠されていることや、見えないことを明らかにする。',
    'likesCount': 9,
    'isPublic': true,
  },
  'definition16': {
    'wordId': 'word14',
    'authorId': 'user16',
    'content': '勤勉とは、一生懸命に努力すること。それは目標を達成するための継続的な取り組みを意味する。',
    'likesCount': 13,
    'isPublic': true,
  },
  'definition17': {
    'wordId': 'word15',
    'authorId': 'user17',
    'content': '情熱とは、強い興奮や感情。何かを達成したいという熱い気持ちや、熱中すること。',
    'likesCount': 8,
    'isPublic': true,
  },
  'definition18': {
    'wordId': 'word16',
    'authorId': 'user18',
    'content':
        '悲しみとは、喪失や失敗などのネガティブな出来事によって感じる感情。しかし、その感情を乗り越えることで、人は成長することができる。',
    'likesCount': 6,
    'isPublic': true,
  },
  'definition19': {
    'wordId': 'word17',
    'authorId': 'user19',
    'content': '喜びとは、何か良いことが起こったときに感じるポジティブな感情。それは小さな日常の出来事から、大きな成功までさまざま。',
    'likesCount': 12,
    'isPublic': true,
  },
  'definition20': {
    'wordId': 'word18',
    'authorId': 'user20',
    'content': '恐怖とは、危険や脅威に対する感じる強い不安や恐れのこと。それは人の安全を守るための本能的な反応である。',
    'likesCount': 10,
    'isPublic': true,
  },
  'definition21': {
    'wordId': 'word19',
    'authorId': 'user1',
    'content': '勝利...それはただの結果。しかし、その背後には無数の努力、汗、そして涙が隠れている。',
    'likesCount': 10,
    'isPublic': true,
  },
  'definition22': {
    'wordId': 'word20',
    'authorId': 'user2',
    'content': '敗北ってさ、結局のところ新たなスタート地点だよね。失敗は成功の元って言うしな！',
    'likesCount': 9,
    'isPublic': true,
  },
  'definition23': {
    'wordId': 'word21',
    'authorId': 'user3',
    'content': '希望は光。闇の中で一筋の光を見つけることができるのは、希望があるからだ。',
    'likesCount': 15,
    'isPublic': true,
  },
  'definition24': {
    'wordId': 'word22',
    'authorId': 'user4',
    'content': '絶望...暗闇に取り込まれてしまう感覚。だけど、その先には必ず明るい未来が待っている。',
    'likesCount': 12,
    'isPublic': true,
  },
  'definition25': {
    'wordId': 'word23',
    'authorId': 'user5',
    'content': '自己とは、自分自身のこと。他人とは違った、唯一無二の存在。自分を大切にし、自分を信じることが大切。',
    'likesCount': 14,
    'isPublic': true,
  },
  'definition26': {
    'wordId': 'word24',
    'authorId': 'user6',
    'content': '他者とは、自分以外の全て。彼らとの関わり合いの中で、自分自身も成長していく。',
    'likesCount': 11,
    'isPublic': true,
  },
  'definition27': {
    'wordId': 'word25',
    'authorId': 'user7',
    'content': '可能性は無限大！限界なんて、自分が作り出すものさ。限界を打破するのは、自分自身の力だ。',
    'likesCount': 13,
    'isPublic': true,
  },
  'definition28': {
    'wordId': 'word26',
    'authorId': 'user8',
    'content': '限界ってのは、試される壁だ。でも、その壁を乗り越えた先には、新しい世界が広がっているんだ。',
    'likesCount': 14,
    'isPublic': true,
  },
  'definition29': {
    'wordId': 'word27',
    'authorId': 'user9',
    'content': '平等とは、皆が同じ価値を持つこと。外見や立場、背景に関係なく、全ての人が平等に扱われるべきだ。',
    'likesCount': 15,
    'isPublic': true,
  },
  'definition30': {
    'wordId': 'word28',
    'authorId': 'user10',
    'content': '差別とは、ある基準に基づいて他者を差別すること。それは誤った価値観に基づいており、許されるものではない。',
    'likesCount': 16,
    'isPublic': true,
  },
  'definition31': {
    'wordId': 'word29',
    'authorId': 'user11',
    'content': '運命って、時々不可解だよね。でも、それに逆らうことで、真の運命を見つけられるかもしれない。',
    'likesCount': 7,
    'isPublic': true,
  },
  'definition32': {
    'wordId': 'word30',
    'authorId': 'user12',
    'content': '信頼とは、他者への深い信念。それは時間をかけて築かれるもので、一度失うと取り戻すのは難しい。',
    'likesCount': 9,
    'isPublic': true,
  },
  'definition33': {
    'wordId': 'word1',
    'authorId': 'user13',
    'content': '友情は宝物。それは、時には言葉にできないほどの強さを持っている。',
    'likesCount': 6,
    'isPublic': true,
  },
  'definition34': {
    'wordId': 'word2',
    'authorId': 'user14',
    'content': '愛とは、時には痛みを伴うが、それを乗り越えることで、真の愛を知ることができる。',
    'likesCount': 8,
    'isPublic': true,
  },
  'definition35': {
    'wordId': 'word3',
    'authorId': 'user15',
    'content': '失敗は、新たなスタートの証。何度でも立ち上がり、前に進む勇気があれば、失敗はただの過程に過ぎない。',
    'likesCount': 10,
    'isPublic': true,
  },
  'definition36': {
    'wordId': 'word4',
    'authorId': 'user16',
    'content': '成功の裏には、数え切れないほどの挑戦と努力がある。目に見えない過程が、最終的な成功を生む。',
    'likesCount': 7,
    'isPublic': true,
  },
  'definition37': {
    'wordId': 'word5',
    'authorId': 'user17',
    'content': '自由とは、束縛から解放されること。それは、自分自身の心の中で見つけることができる。',
    'likesCount': 5,
    'isPublic': true,
  },
  'definition38': {
    'wordId': 'word6',
    'authorId': 'user18',
    'content':
        '平和は、戦争や争いのない状態だけではなく、心の中の平穏を指すこともある。内なる平和を見つけることが、外の世界に平和をもたらす第一歩だ。',
    'likesCount': 9,
    'isPublic': true,
  },
  'definition39': {
    'wordId': 'word7',
    'authorId': 'user19',
    'content': '冒険は、未知の世界への挑戦。それは、新たな発見や経験を通じて、自分自身も成長することができる。',
    'likesCount': 8,
    'isPublic': true,
  },
  'definition40': {
    'wordId': 'word8',
    'authorId': 'user20',
    'content': '夢は、目指すべき方向。それを追い続けることで、人は限界を打破することができる。',
    'likesCount': 10,
    'isPublic': true,
  },
  'definition41': {
    'wordId': 'word9',
    'authorId': 'user1',
    'content': '希望とは、明日の朝ごはんへの期待。石田スミレの希望は、朝のクロワッサンとカフェラテ。あ、でも、週末のセールも外せない。',
    'likesCount': 11,
    'isPublic': true,
  },
  'definition42': {
    'wordId': 'word10',
    'authorId': 'user2',
    'content': '勇気とは、最後の1ピースを奪い合うこと。ルフィは、仲間との食事で、その勇気を毎回試されていると語っている。',
    'likesCount': 13,
    'isPublic': true,
  },
  'definition43': {
    'wordId': 'word11',
    'authorId': 'user3',
    'content': '哲学？ナルトは「ラーメンの最後の1滴まで飲むこと」それが彼の哲学。味噌、醤油、塩、全部大好き！',
    'likesCount': 9,
    'isPublic': true,
  },
  'definition44': {
    'wordId': 'word12',
    'authorId': 'user4',
    'content': 'アトムの信仰はシンプル。正義のため、そして友達の笑顔のために戦うこと。でも、時々オイルが欲しくなる。',
    'likesCount': 10,
    'isPublic': true,
  },
  'definition45': {
    'wordId': 'word13',
    'authorId': 'user5',
    'content': '真実ってなんだろう。一護にとって真実は、友達との絆。そして、時々の甘いドーナツの誘惑。そう、それも真実。',
    'likesCount': 12,
    'isPublic': true,
  },
};
