// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/definition_list/application/definition_id_list_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_annotation/riverpod_annotation.dart' as _i13;
import 'package:teigi_app/feature/definition_list/domain/definition_id_list_state.dart'
    as _i3;
import 'package:teigi_app/feature/definition_list/repository/definition_id_list_repository.dart'
    as _i5;
import 'package:teigi_app/feature/definition_list/util/definition_feed_type.dart'
    as _i7;
import 'package:teigi_app/feature/user_config/repository/user_config_repository.dart'
    as _i10;
import 'package:teigi_app/feature/user_follow/repository/user_follow_repository.dart'
    as _i11;
import 'package:teigi_app/feature/user_profile/domain/user_profile.dart' as _i4;
import 'package:teigi_app/feature/user_profile/repository/user_profile_repository.dart'
    as _i9;
import 'package:teigi_app/util/constant/initial_main_group.dart' as _i8;

import 'definition_id_list_state_test.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDefinitionIdListState_1 extends _i1.SmartFake
    implements _i3.DefinitionIdListState {
  _FakeDefinitionIdListState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserProfile_2 extends _i1.SmartFake implements _i4.UserProfile {
  _FakeUserProfile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DefinitionIdListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefinitionIdListRepository extends _i1.Mock
    implements _i5.DefinitionIdListRepository {
  @override
  _i2.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
            returnValueForMissingStub: _FakeFirebaseFirestore_0(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i2.FirebaseFirestore);

  @override
  _i6.Future<_i3.DefinitionIdListState> fetchForHomeRecommend(
    String? currentUserId,
    List<String>? mutedUserIdList,
    _i2.QueryDocumentSnapshot<Object?>? lastDocument,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForHomeRecommend, [
              currentUserId,
              mutedUserIdList,
              lastDocument,
            ]),
            returnValue: _i6.Future<_i3.DefinitionIdListState>.value(
              _FakeDefinitionIdListState_1(
                this,
                Invocation.method(#fetchForHomeRecommend, [
                  currentUserId,
                  mutedUserIdList,
                  lastDocument,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.DefinitionIdListState>.value(
                  _FakeDefinitionIdListState_1(
                    this,
                    Invocation.method(#fetchForHomeRecommend, [
                      currentUserId,
                      mutedUserIdList,
                      lastDocument,
                    ]),
                  ),
                ),
          )
          as _i6.Future<_i3.DefinitionIdListState>);

  @override
  _i6.Future<_i3.DefinitionIdListState> fetchForHomeFollowing(
    String? currentUserId,
    List<String>? targetUserIdList,
    _i2.QueryDocumentSnapshot<Object?>? lastDocument,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForHomeFollowing, [
              currentUserId,
              targetUserIdList,
              lastDocument,
            ]),
            returnValue: _i6.Future<_i3.DefinitionIdListState>.value(
              _FakeDefinitionIdListState_1(
                this,
                Invocation.method(#fetchForHomeFollowing, [
                  currentUserId,
                  targetUserIdList,
                  lastDocument,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.DefinitionIdListState>.value(
                  _FakeDefinitionIdListState_1(
                    this,
                    Invocation.method(#fetchForHomeFollowing, [
                      currentUserId,
                      targetUserIdList,
                      lastDocument,
                    ]),
                  ),
                ),
          )
          as _i6.Future<_i3.DefinitionIdListState>);

  @override
  _i6.Future<_i3.DefinitionIdListState> fetchForWordTop(
    _i7.WordTopOrderByType? orderByType,
    String? currentUserId,
    List<String>? mutedUserIdList,
    String? wordId,
    _i2.QueryDocumentSnapshot<Object?>? lastDocument,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForWordTop, [
              orderByType,
              currentUserId,
              mutedUserIdList,
              wordId,
              lastDocument,
            ]),
            returnValue: _i6.Future<_i3.DefinitionIdListState>.value(
              _FakeDefinitionIdListState_1(
                this,
                Invocation.method(#fetchForWordTop, [
                  orderByType,
                  currentUserId,
                  mutedUserIdList,
                  wordId,
                  lastDocument,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.DefinitionIdListState>.value(
                  _FakeDefinitionIdListState_1(
                    this,
                    Invocation.method(#fetchForWordTop, [
                      orderByType,
                      currentUserId,
                      mutedUserIdList,
                      wordId,
                      lastDocument,
                    ]),
                  ),
                ),
          )
          as _i6.Future<_i3.DefinitionIdListState>);

  @override
  _i6.Future<_i3.DefinitionIdListState> fetchForProfileCreatedAt(
    String? currentUserId,
    String? targetUserId,
    _i2.QueryDocumentSnapshot<Object?>? lastDocument,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForProfileCreatedAt, [
              currentUserId,
              targetUserId,
              lastDocument,
            ]),
            returnValue: _i6.Future<_i3.DefinitionIdListState>.value(
              _FakeDefinitionIdListState_1(
                this,
                Invocation.method(#fetchForProfileCreatedAt, [
                  currentUserId,
                  targetUserId,
                  lastDocument,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.DefinitionIdListState>.value(
                  _FakeDefinitionIdListState_1(
                    this,
                    Invocation.method(#fetchForProfileCreatedAt, [
                      currentUserId,
                      targetUserId,
                      lastDocument,
                    ]),
                  ),
                ),
          )
          as _i6.Future<_i3.DefinitionIdListState>);

  @override
  _i6.Future<_i3.DefinitionIdListState> fetchForLikedByUser(
    String? currentUserId,
    String? targetUserId,
    List<String>? mutedUserIdList,
    _i2.QueryDocumentSnapshot<Object?>? initialLastDocument,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForLikedByUser, [
              currentUserId,
              targetUserId,
              mutedUserIdList,
              initialLastDocument,
            ]),
            returnValue: _i6.Future<_i3.DefinitionIdListState>.value(
              _FakeDefinitionIdListState_1(
                this,
                Invocation.method(#fetchForLikedByUser, [
                  currentUserId,
                  targetUserId,
                  mutedUserIdList,
                  initialLastDocument,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.DefinitionIdListState>.value(
                  _FakeDefinitionIdListState_1(
                    this,
                    Invocation.method(#fetchForLikedByUser, [
                      currentUserId,
                      targetUserId,
                      mutedUserIdList,
                      initialLastDocument,
                    ]),
                  ),
                ),
          )
          as _i6.Future<_i3.DefinitionIdListState>);

  @override
  _i6.Future<_i3.DefinitionIdListState> fetchForIndividualDictionary(
    String? currentUserId,
    String? targetUserId,
    _i8.InitialSubGroup? initialSubGroup,
    _i2.QueryDocumentSnapshot<Object?>? lastDocument,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchForIndividualDictionary, [
              currentUserId,
              targetUserId,
              initialSubGroup,
              lastDocument,
            ]),
            returnValue: _i6.Future<_i3.DefinitionIdListState>.value(
              _FakeDefinitionIdListState_1(
                this,
                Invocation.method(#fetchForIndividualDictionary, [
                  currentUserId,
                  targetUserId,
                  initialSubGroup,
                  lastDocument,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i6.Future<_i3.DefinitionIdListState>.value(
                  _FakeDefinitionIdListState_1(
                    this,
                    Invocation.method(#fetchForIndividualDictionary, [
                      currentUserId,
                      targetUserId,
                      initialSubGroup,
                      lastDocument,
                    ]),
                  ),
                ),
          )
          as _i6.Future<_i3.DefinitionIdListState>);
}

/// A class which mocks [UserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepository extends _i1.Mock
    implements _i9.UserProfileRepository {
  @override
  _i6.Future<_i4.UserProfile> fetchUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserProfile, [userId]),
            returnValue: _i6.Future<_i4.UserProfile>.value(
              _FakeUserProfile_2(
                this,
                Invocation.method(#fetchUserProfile, [userId]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.UserProfile>.value(
              _FakeUserProfile_2(
                this,
                Invocation.method(#fetchUserProfile, [userId]),
              ),
            ),
          )
          as _i6.Future<_i4.UserProfile>);

  @override
  _i6.Future<void> updateUserProfile(_i4.UserProfile? userProfileForWrite) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserProfile, [userProfileForWrite]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [UserConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserConfigRepository extends _i1.Mock
    implements _i10.UserConfigRepository {
  @override
  _i6.Future<List<String>> fetchMutedUserIdList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMutedUserIdList, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> appendMutedUserIdList(String? mutedUserId) =>
      (super.noSuchMethod(
            Invocation.method(#appendMutedUserIdList, [mutedUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeMutedUserIdList(String? mutedUserId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMutedUserIdList, [mutedUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [UserFollowRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserFollowRepository extends _i1.Mock
    implements _i11.UserFollowRepository {
  @override
  _i6.Future<void> follow(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#follow, [targetUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> unfollow(String? targetUserId) =>
      (super.noSuchMethod(
            Invocation.method(#unfollow, [targetUserId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>> fetchAllFollowingIdList(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllFollowingIdList, [userId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);
}

/// A class which mocks [Listener].
///
/// See the documentation for Mockito's code generation for more information.
class MockListener extends _i1.Mock
    implements _i12.Listener<_i13.AsyncValue<_i3.DefinitionIdListState>> {
  @override
  void call(
    _i13.AsyncValue<_i3.DefinitionIdListState>? previous,
    _i13.AsyncValue<_i3.DefinitionIdListState>? next,
  ) => super.noSuchMethod(
    Invocation.method(#call, [previous, next]),
    returnValueForMissingStub: null,
  );
}
