// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/word/application/word_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:teigi_app/feature/word/domain/word.dart' as _i4;
import 'package:teigi_app/feature/word/repository/word_repository.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [WordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordRepository extends _i1.Mock implements _i2.WordRepository {
  @override
  _i3.Future<_i4.Word?> fetchWordById(String? wordId) => (super.noSuchMethod(
        Invocation.method(
          #fetchWordById,
          [wordId],
        ),
        returnValue: _i3.Future<_i4.Word?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.Word?>.value(),
      ) as _i3.Future<_i4.Word?>);

  @override
  _i3.Future<void> save(String? wordId) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [wordId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> unsave(String? wordId) => (super.noSuchMethod(
        Invocation.method(
          #unsave,
          [wordId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
