// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/word/application/word_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:teigi_app/feature/word/domain/word.dart' as _i2;
import 'package:teigi_app/feature/word/repository/word_repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWord_0 extends _i1.SmartFake implements _i2.Word {
  _FakeWord_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WordRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWordRepository extends _i1.Mock implements _i3.WordRepository {
  @override
  _i4.Future<_i2.Word?> fetchWordById(String? wordId) => (super.noSuchMethod(
        Invocation.method(
          #fetchWordById,
          [wordId],
        ),
        returnValue: _i4.Future<_i2.Word?>.value(),
        returnValueForMissingStub: _i4.Future<_i2.Word?>.value(),
      ) as _i4.Future<_i2.Word?>);

  @override
  _i4.Future<void> save(String? wordId) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [wordId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> unsave(String? wordId) => (super.noSuchMethod(
        Invocation.method(
          #unsave,
          [wordId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.Word> update({
    required String? wordId,
    required String? word,
    required String? reading,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [],
          {
            #wordId: wordId,
            #word: word,
            #reading: reading,
          },
        ),
        returnValue: _i4.Future<_i2.Word>.value(_FakeWord_0(
          this,
          Invocation.method(
            #update,
            [],
            {
              #wordId: wordId,
              #word: word,
              #reading: reading,
            },
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Word>.value(_FakeWord_0(
          this,
          Invocation.method(
            #update,
            [],
            {
              #wordId: wordId,
              #word: word,
              #reading: reading,
            },
          ),
        )),
      ) as _i4.Future<_i2.Word>);
}
