// Mocks generated by Mockito 5.4.6 from annotations
// in teigi_app/test/feature/force_event/repository/app_config_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:teigiii_api/src/api/app_config_api.dart' as _i3;
import 'package:teigiii_api/src/model/app_config_response.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppConfigApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppConfigApi extends _i1.Mock implements _i3.AppConfigApi {
  @override
  _i4.Future<_i2.Response<_i5.AppConfigResponse>> v1AppConfigGet({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#v1AppConfigGet, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue: _i4.Future<_i2.Response<_i5.AppConfigResponse>>.value(
              _FakeResponse_0<_i5.AppConfigResponse>(
                this,
                Invocation.method(#v1AppConfigGet, [], {
                  #cancelToken: cancelToken,
                  #headers: headers,
                  #extra: extra,
                  #validateStatus: validateStatus,
                  #onSendProgress: onSendProgress,
                  #onReceiveProgress: onReceiveProgress,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Response<_i5.AppConfigResponse>>.value(
                  _FakeResponse_0<_i5.AppConfigResponse>(
                    this,
                    Invocation.method(#v1AppConfigGet, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Response<_i5.AppConfigResponse>>);
}
