// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/user_config/user_config_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:teigi_app/feature/user_config/repository/package_info_repository.dart'
    as _i4;
import 'package:teigi_app/feature/user_config/repository/user_config_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserConfigRepository extends _i1.Mock
    implements _i2.UserConfigRepository {
  @override
  _i3.Future<List<String>> fetchMutedUserIdList() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMutedUserIdList, []),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i3.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<void> appendMutedUserIdList(String? mutedUserId) =>
      (super.noSuchMethod(
            Invocation.method(#appendMutedUserIdList, [mutedUserId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeMutedUserIdList(String? mutedUserId) =>
      (super.noSuchMethod(
            Invocation.method(#removeMutedUserIdList, [mutedUserId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [PackageInfoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPackageInfoRepository extends _i1.Mock
    implements _i4.PackageInfoRepository {
  @override
  _i3.Future<String> fetchAppVersion() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAppVersion, []),
            returnValue: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#fetchAppVersion, []),
              ),
            ),
            returnValueForMissingStub: _i3.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#fetchAppVersion, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<int> fetchBuildNumber() =>
      (super.noSuchMethod(
            Invocation.method(#fetchBuildNumber, []),
            returnValue: _i3.Future<int>.value(0),
            returnValueForMissingStub: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}
