// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/timeline/application/discover_timeline_state_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:teigi_app/feature/timeline/domain/discover_feed_list_state.dart'
    as _i2;
import 'package:teigi_app/feature/timeline/repository/discover_timeline_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDiscoverFeedListState_0 extends _i1.SmartFake
    implements _i2.DiscoverFeedListState {
  _FakeDiscoverFeedListState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DiscoverTimelineRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiscoverTimelineRepository extends _i1.Mock
    implements _i3.DiscoverTimelineRepository {
  @override
  _i4.Future<_i2.DiscoverFeedListState> fetchDiscoverTimeline(String? cursor) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDiscoverTimeline, [cursor]),
            returnValue: _i4.Future<_i2.DiscoverFeedListState>.value(
              _FakeDiscoverFeedListState_0(
                this,
                Invocation.method(#fetchDiscoverTimeline, [cursor]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.DiscoverFeedListState>.value(
                  _FakeDiscoverFeedListState_0(
                    this,
                    Invocation.method(#fetchDiscoverTimeline, [cursor]),
                  ),
                ),
          )
          as _i4.Future<_i2.DiscoverFeedListState>);
}
