// Mocks generated by Mockito 5.4.4 from annotations
// in teigi_app/test/feature/personal_dictionary/repository/personal_dictionary_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:teigi_app/feature/definition/domain/definition_draft.dart'
    as _i3;
import 'package:teigi_app/feature/definition/repository/definition_draft_repository.dart'
    as _i11;
import 'package:teigiii_api/src/model/my_dictionary_overview.dart' as _i8;
import 'package:teigiii_api/src/model/v1_me_defined_words_get200_response.dart'
    as _i6;
import 'package:teigiii_api/src/model/v1_me_saved_words_get200_response.dart'
    as _i10;
import 'package:teigiii_api/src/model/v1_users_id_definitions_get200_response.dart'
    as _i7;
import 'package:teigiii_api/src/model/v1_users_id_followers_get200_response.dart'
    as _i9;
import 'package:teigiii_api/teigiii_api.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDefinitionDraft_1 extends _i1.SmartFake
    implements _i3.DefinitionDraft {
  _FakeDefinitionDraft_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MeApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMeApi extends _i1.Mock implements _i4.MeApi {
  @override
  _i5.Future<
      _i2.Response<_i6.V1MeDefinedWordsGet200Response>> v1MeDefinedWordsGet({
    String? cursor,
    int? limit = 20,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1MeDefinedWordsGet,
          [],
          {
            #cursor: cursor,
            #limit: limit,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i2.Response<_i6.V1MeDefinedWordsGet200Response>>.value(
                _FakeResponse_0<_i6.V1MeDefinedWordsGet200Response>(
          this,
          Invocation.method(
            #v1MeDefinedWordsGet,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Response<_i6.V1MeDefinedWordsGet200Response>>.value(
                _FakeResponse_0<_i6.V1MeDefinedWordsGet200Response>(
          this,
          Invocation.method(
            #v1MeDefinedWordsGet,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<_i6.V1MeDefinedWordsGet200Response>>);

  @override
  _i5.Future<
      _i2.Response<_i7.V1UsersIdDefinitionsGet200Response>> v1MeDefinitionsGet({
    String? cursor,
    int? limit = 20,
    String? status,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1MeDefinitionsGet,
          [],
          {
            #cursor: cursor,
            #limit: limit,
            #status: status,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5
            .Future<_i2.Response<_i7.V1UsersIdDefinitionsGet200Response>>.value(
            _FakeResponse_0<_i7.V1UsersIdDefinitionsGet200Response>(
          this,
          Invocation.method(
            #v1MeDefinitionsGet,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #status: status,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub: _i5
            .Future<_i2.Response<_i7.V1UsersIdDefinitionsGet200Response>>.value(
            _FakeResponse_0<_i7.V1UsersIdDefinitionsGet200Response>(
          this,
          Invocation.method(
            #v1MeDefinitionsGet,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #status: status,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<_i7.V1UsersIdDefinitionsGet200Response>>);

  @override
  _i5.Future<_i2.Response<_i8.MyDictionaryOverview>> v1MeDictionaryOverviewGet({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1MeDictionaryOverviewGet,
          [],
          {
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i2.Response<_i8.MyDictionaryOverview>>.value(
            _FakeResponse_0<_i8.MyDictionaryOverview>(
          this,
          Invocation.method(
            #v1MeDictionaryOverviewGet,
            [],
            {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Response<_i8.MyDictionaryOverview>>.value(
                _FakeResponse_0<_i8.MyDictionaryOverview>(
          this,
          Invocation.method(
            #v1MeDictionaryOverviewGet,
            [],
            {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<_i8.MyDictionaryOverview>>);

  @override
  _i5.Future<_i2.Response<_i9.V1UsersIdFollowersGet200Response>> v1MeMutesGet({
    String? cursor,
    int? limit = 20,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1MeMutesGet,
          [],
          {
            #cursor: cursor,
            #limit: limit,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5
            .Future<_i2.Response<_i9.V1UsersIdFollowersGet200Response>>.value(
            _FakeResponse_0<_i9.V1UsersIdFollowersGet200Response>(
          this,
          Invocation.method(
            #v1MeMutesGet,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub: _i5
            .Future<_i2.Response<_i9.V1UsersIdFollowersGet200Response>>.value(
            _FakeResponse_0<_i9.V1UsersIdFollowersGet200Response>(
          this,
          Invocation.method(
            #v1MeMutesGet,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<_i9.V1UsersIdFollowersGet200Response>>);

  @override
  _i5.Future<
      _i2.Response<_i10.V1MeSavedWordsGet200Response>> v1MeSavedWordsGet({
    String? cursor,
    int? limit = 20,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #v1MeSavedWordsGet,
          [],
          {
            #cursor: cursor,
            #limit: limit,
            #cancelToken: cancelToken,
            #headers: headers,
            #extra: extra,
            #validateStatus: validateStatus,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue:
            _i5.Future<_i2.Response<_i10.V1MeSavedWordsGet200Response>>.value(
                _FakeResponse_0<_i10.V1MeSavedWordsGet200Response>(
          this,
          Invocation.method(
            #v1MeSavedWordsGet,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Response<_i10.V1MeSavedWordsGet200Response>>.value(
                _FakeResponse_0<_i10.V1MeSavedWordsGet200Response>(
          this,
          Invocation.method(
            #v1MeSavedWordsGet,
            [],
            {
              #cursor: cursor,
              #limit: limit,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i2.Response<_i10.V1MeSavedWordsGet200Response>>);
}

/// A class which mocks [DefinitionDraftRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDefinitionDraftRepository extends _i1.Mock
    implements _i11.DefinitionDraftRepository {
  @override
  _i5.Future<_i3.DefinitionDraft> save(_i3.DefinitionDraft? draft) =>
      (super.noSuchMethod(
        Invocation.method(
          #save,
          [draft],
        ),
        returnValue:
            _i5.Future<_i3.DefinitionDraft>.value(_FakeDefinitionDraft_1(
          this,
          Invocation.method(
            #save,
            [draft],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.DefinitionDraft>.value(_FakeDefinitionDraft_1(
          this,
          Invocation.method(
            #save,
            [draft],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionDraft>);

  @override
  _i5.Future<_i3.DefinitionDraft> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue:
            _i5.Future<_i3.DefinitionDraft>.value(_FakeDefinitionDraft_1(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.DefinitionDraft>.value(_FakeDefinitionDraft_1(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i5.Future<_i3.DefinitionDraft>);

  @override
  _i5.Future<({List<_i3.DefinitionDraft> items, String? nextCursor})> list({
    String? cursor,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [],
          {
            #cursor: cursor,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<
            ({
              List<_i3.DefinitionDraft> items,
              String? nextCursor
            })>.value((items: <_i3.DefinitionDraft>[], nextCursor: null)),
        returnValueForMissingStub: _i5.Future<
            ({
              List<_i3.DefinitionDraft> items,
              String? nextCursor
            })>.value((items: <_i3.DefinitionDraft>[], nextCursor: null)),
      ) as _i5.Future<({List<_i3.DefinitionDraft> items, String? nextCursor})>);

  @override
  _i5.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> finalize(
    String? id, {
    bool? confirmReadingMismatch = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #finalize,
          [id],
          {#confirmReadingMismatch: confirmReadingMismatch},
        ),
        returnValue: _i5.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #finalize,
            [id],
            {#confirmReadingMismatch: confirmReadingMismatch},
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<String>.value(_i12.dummyValue<String>(
          this,
          Invocation.method(
            #finalize,
            [id],
            {#confirmReadingMismatch: confirmReadingMismatch},
          ),
        )),
      ) as _i5.Future<String>);
}
