// Mocks generated by Mockito 5.4.6 from annotations
// in teigi_app/test/core/telemetry/perf_telemetry_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:teigi_app/core/telemetry/frame_stats_client.dart' as _i2;
import 'package:teigi_app/core/telemetry/screen_frame_stats.dart' as _i5;
import 'package:teigiii_api/teigiii_api.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [FrameStatsClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockFrameStatsClient extends _i1.Mock implements _i2.FrameStatsClient {
  @override
  _i3.Future<void> send({
    required String? sessionId,
    required _i4.FrameStatsDevice? device,
    required List<_i5.ScreenFrameStats>? stats,
    required DateTime? recordedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#send, [], {
              #sessionId: sessionId,
              #device: device,
              #stats: stats,
              #recordedAt: recordedAt,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
