name: bump pull request

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: Please Choice Bump Target
        default: build
        options:
          - build
          - patch
          - minor
          - major

env:
  GIT_USER_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  GIT_USER_NAME: 'github-actions[bot]'

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Install dependencies
        run: nix develop --command just setup

      - name: Init git config
        run: |
          git config --local user.name "$GIT_USER_NAME"
          git config --local user.email "$GIT_USER_EMAIL"

      - name: Bump version
        run: |
          nix develop --command bash -c 'cd mobile_app && dart run cider bump "${{ github.event.inputs.bump }}" --bump-build'
          echo "BUMP_VERSION=$(nix develop --command bash -c 'cd mobile_app && dart run cider version')" >> "$GITHUB_ENV"

      - name: Commit pubspec.yaml
        run: |
          git checkout develop
          git add -u mobile_app/pubspec.yaml
          echo "Bumped version number to $BUMP_VERSION" | git commit --file=-

      - name: Create release branch
        run: |
          git checkout -b "releases/$BUMP_VERSION"
          echo "RELEASE_BRANCH=releases/$BUMP_VERSION" >> "$GITHUB_ENV"

      - name: Push branch
        run: git push -u origin "$RELEASE_BRANCH"

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create -B develop -t "Release $BUMP_VERSION" -b "Release $BUMP_VERSION" --head "$RELEASE_BRANCH"
