name: check

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Create dot env file
        run: touch .env

      - name: Install dependencies
        run: nix develop --command just setup

      - name: Analyze
        run: nix develop --command just analyze

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Create dot env file
        run: touch .env

      - name: Install dependencies
        run: nix develop --command just setup

      - name: Test
        run: nix develop --command just test
