// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, combinators_ordering, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web QA 用。apiKey / appId は Firebase console で Web アプリ登録後に
  /// `--dart-define` / `dart_defines/dev.json` で注入する。
  static FirebaseOptions get web {
    const apiKey = String.fromEnvironment('FIREBASE_WEB_API_KEY');
    const appId = String.fromEnvironment('FIREBASE_WEB_APP_ID');
    if (apiKey.isEmpty || appId.isEmpty) {
      throw UnsupportedError(
        'DefaultFirebaseOptions for web require FIREBASE_WEB_API_KEY and '
        'FIREBASE_WEB_APP_ID dart-defines. Register a Web app in the '
        'everyone-teigi-dev Firebase project and pass the values.',
      );
    }
    return const FirebaseOptions(
      apiKey: apiKey,
      appId: appId,
      messagingSenderId: '225028441501',
      projectId: 'everyone-teigi-dev',
      authDomain: 'everyone-teigi-dev.firebaseapp.com',
      storageBucket: 'everyone-teigi-dev.appspot.com',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3U45McsnonOHdoyD8JnZdIbuwkblxlDs',
    appId: '1:225028441501:android:262a05ffa053eddbb5db74',
    messagingSenderId: '225028441501',
    projectId: 'everyone-teigi-dev',
    storageBucket: 'everyone-teigi-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQJqCl67hpyhCVD8wz82IQbw5l8nLv8xs',
    appId: '1:225028441501:ios:370c06ac8f1486b7b5db74',
    messagingSenderId: '225028441501',
    projectId: 'everyone-teigi-dev',
    storageBucket: 'everyone-teigi-dev.appspot.com',
    iosBundleId: 'com.toda.teigiii.dev',
  );
}
